server:
  port: 8080

config-service:
  url: ${CONFIG_SERVICE_URL:http://localhost:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/frauddb}
    username: ${DB_USERNAME:fraud}
    password: ${DB_PASSWORD:fraud}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

fraud:
  alert:
    exchange: fraud.exchange
    routing-key: fraud.alert

logging:
  level:
    root: INFO
    com.fraud: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
